CREATE TABLE FILEBOARD(
	NUM NUMBER(5),
	NAME VARCHAR2(20),
	TITLE VARCHAR2(100),
	CONTENT VARCHAR2(1000),
	REGDATE DATE
);

CREATE SEQUENCE FILEBOARDNUM_SEQ;

CREATE TABLE FILEDATA(
	NUM NUMBER(5),
    BOARDNUM NUMBER(5),
	ORINAME VARCHAR2(500),
    CHGNAME VARCHAR2(500),
	REGDATE DATE,
    USAGE NUMBER(1)
);

CREATE SEQUENCE FILEDATANUM_SEQ;

CREATE SEQUENCE FILEBOARDNUM_SEQ;